import Head from "next/head";
import { Inter } from "next/font/google";
import Card from "../components/Card";
import Header from "@/components/Header";
import MainArea from "@/components/MainArea";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" space-y-3">
        <h1 className="text-2xl gradient-text">
          Dashboard is going to be fun and i am going to love it which is most
          important
        </h1>
      </main>
    </>
  );
}
